import puppeteer from "puppeteer-core";
const EDGE = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
const browser = await puppeteer.launch({ executablePath: EDGE, headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
const errs = [];
page.on('pageerror', e => errs.push(e.message));
await page.goto("http://localhost:8000/index-m.html", { waitUntil: "networkidle0", timeout: 60000 });
await new Promise(r => setTimeout(r, 1200));
const home = await page.evaluate(() => {
  const active = [...document.querySelectorAll(".page.active")].map(p => p.id);
  const homeH = document.getElementById("page-home").getBoundingClientRect().height;
  const banner = document.querySelector(".hero-banner").getBoundingClientRect().height;
  const portal = document.querySelector(".hero-portal").getBoundingClientRect().height;
  const pmCols = getComputedStyle(document.querySelector(".pm-grid")).gridTemplateColumns;
  return { active, homeH: Math.round(homeH), banner: Math.round(banner), portal: Math.round(portal), pmCols, onHome: document.body.classList.contains("on-home"), bodyH: document.body.scrollHeight, vh: window.innerHeight };
});
console.log("HOME:", JSON.stringify(home));
await page.screenshot({ path: "D:/新文科比赛/高邮网站/gaoyou-pages/screenshots/spa-m-home.png", fullPage: false });
await page.evaluate(() => { const a = document.querySelector('.menu-overlay a[data-page="explore"]'); a.click(); });
await new Promise(r => setTimeout(r, 600));
const ex = await page.evaluate(() => ({ active: [...document.querySelectorAll(".page.active")].map(p => p.id), menuOpen: document.getElementById("menuOverlay").classList.contains("open"), scrollY: window.scrollY }));
console.log("EXPLORE:", JSON.stringify(ex));
await page.evaluate(() => window.showPage("map"));
await new Promise(r => setTimeout(r, 2200));
const map = await page.evaluate(() => ({ hasMap: !!window.__gyMap, size: (() => { const b = document.getElementById("heritage-map").getBoundingClientRect(); return Math.round(b.width) + "x" + Math.round(b.height); })(), active: [...document.querySelectorAll(".page.active")].map(p => p.id) }));
console.log("MAP:", JSON.stringify(map));
await page.evaluate(() => window.showPage("survey"));
await new Promise(r => setTimeout(r, 1000));
const surv = await page.evaluate(() => ({ charts: (window.__charts||[]).length }));
console.log("SURVEY:", JSON.stringify(surv));
await page.evaluate(() => window.showPage("home"));
await new Promise(r => setTimeout(r, 300));
await page.screenshot({ path: "D:/新文科比赛/高邮网站/gaoyou-pages/screenshots/spa-m-home2.png", fullPage: false });
console.log("ERRORS:", JSON.stringify(errs));
await browser.close();
