import puppeteer from "puppeteer-core";
const EDGE = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
const browser = await puppeteer.launch({ executablePath: EDGE, headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1.5 });
const errs = [];
page.on('pageerror', e => errs.push(e.message));
await page.goto("http://localhost:8000/index.html?desktop=1", { waitUntil: "networkidle0", timeout: 60000 });
await new Promise(r => setTimeout(r, 1200));
await page.screenshot({ path: "D:/新文科比赛/高邮网站/gaoyou-pages/screenshots/FINAL-home-desktop.png", fullPage: false });
const d = await page.evaluate(() => ({ homeH: Math.round(document.getElementById("page-home").getBoundingClientRect().height), bodyH: document.body.scrollHeight, vh: window.innerHeight, active: [...document.querySelectorAll(".page.active")].map(p => p.id) }));
console.log("DESKTOP HOME:", JSON.stringify(d));
await page.evaluate(() => document.querySelector('.nav a[data-page="explore"]').click());
await new Promise(r => setTimeout(r, 600));
const d2 = await page.evaluate(() => ({ active: [...document.querySelectorAll(".page.active")].map(p => p.id), scrollY: window.scrollY }));
console.log("DESKTOP NAV->EXPLORE:", JSON.stringify(d2));
await page.screenshot({ path: "D:/新文科比赛/高邮网站/gaoyou-pages/screenshots/FINAL-explore-desktop.png", clip: { x: 0, y: 0, width: 1440, height: 1000 } });
const m = await browser.newPage();
await m.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
const merrs = [];
m.on('pageerror', e => merrs.push(e.message));
await m.goto("http://localhost:8000/index-m.html", { waitUntil: "networkidle0", timeout: 60000 });
await new Promise(r => setTimeout(r, 1000));
await m.screenshot({ path: "D:/新文科比赛/高邮网站/gaoyou-pages/screenshots/FINAL-home-mobile.png", fullPage: false });
const mm = await m.evaluate(() => ({ homeH: Math.round(document.getElementById("page-home").getBoundingClientRect().height), vh: window.innerHeight, active: [...document.querySelectorAll(".page.active")].map(p => p.id) }));
console.log("MOBILE HOME:", JSON.stringify(mm));
await m.evaluate(() => window.showPage("routes"));
await new Promise(r => setTimeout(r, 600));
await m.screenshot({ path: "D:/新文科比赛/高邮网站/gaoyou-pages/screenshots/FINAL-routes-mobile.png", clip: { x: 0, y: 0, width: 390, height: 900 } });
console.log("ERRORS desktop:", JSON.stringify(errs), "mobile:", JSON.stringify(merrs));
await browser.close();
